[workspace]
members = [
    "cargo_marker",
    "marker_adapter",
    "marker_api",
    "marker_driver_rustc",
    # This is temporary, lint crates like this one will be managed with `cargo-liner`
    "marker_lints",
]
