comment_width              = 100
edition                    = "2021"
error_on_line_overflow     = true
match_block_trailing_comma = true
max_width                  = 120
version                    = "Two"
wrap_comments              = true
