name: Suggest A Feature
description: Suggest a new feature
title: "[Feat]: "
labels: ["C-enhancement", "S-needs-triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for suggesting a feature! 🪄
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        Describe the feature or addition you would like to see.
        Please include a use case of this feature or describe the motivation behind this suggestion.
