name: ci

on:
  push:
    branches:
      - master
  merge_group:
  pull_request:
    # Don't run tests, when only text files were modified
    paths-ignore:
      - 'COPYRIGHT'
      - 'LICENSE-*'
      - '**.md'
      - '**.txt'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: --deny warnings
  RUSTFLAGS: --deny warnings

jobs:
  rust-lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Setup
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with: { toolchain: nightly-2023-07-13 }

      - run: cargo test
      - run: cargo clippy
      - run: cargo fmt --check
      - run: cargo doc --no-deps

  # This task ensures, required packages can be built with a stable toolchain
  # the only package requiring nightly should be `marker_rustc_driver` and
  # optionally `marker_adapter`
  rust-crates-build-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - run: rm rust-toolchain
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo check --exclude marker_rustc_driver --exclude marker_adapter

  # Check the formatting of TOML files in the repository
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/taplo.sh
      - run: ./taplo fmt --check

  # Check for typos in the repository based on a static dictionary
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/typos.sh
      - run: ./typos

  # Check for unused dependencies that uses simple regex search,
  # meaning it's ⚡️ blazingly ⚡️ fast
  rust-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/cargo-machete.sh
      - run: ./cargo-machete
